name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix. v22.14.0 }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix. v22.14.0 }}

    - name: Build
      run: |
        npm install
        npx webpack
